import Footer from '@/components/layout/Footer/Footer'
import Header from '@/components/layout/Header/Header'
import { AuthProvider } from '@/context/AuthContext'
import { CartProvider } from '@/context/CartContext'
import { OrderProvider } from '@/context/OrderContext'
import { WishlistProvider } from '@/context/WishListContext'
import { getCategories } from '@/services/filters'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'

const interSans = Inter({
	variable: '--font-inter-sans',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default async function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	const categories = await getCategories()
	return (
		<html lang='en'>
			<body className={`${interSans.variable} antialiased`}>
				<AuthProvider>
					<OrderProvider>
						<WishlistProvider>
							<CartProvider>
								<Providers>
									<Header categories={categories} />
									{children}
									<Footer />
								</Providers>
							</CartProvider>
						</WishlistProvider>
					</OrderProvider>
				</AuthProvider>
			</body>
		</html>
	)
}
